### ISSUE TITLE
Add Scale Factor read and write register

### ISSUE THREAD

**Issue by Pascalx77** [sclavel/homebridge-modbus#3]
Hi, 

First, thank you for this Plugins, I use it at my Home really, really great. I am new with homebridge and Github, I am discovering this.

I was wondering how to implement an advance feature for read and write register, to add a scale factor.
Example: The value in my ModbusTCP device are in tenth of degre celcius, 21.3 degC = 213.
With a scale factor I could enter 0.1 to correct the value and vice-versa for setpoint enter 10.

Or is there is an other simpler solution?

Regards,

**Comment by berkus** [comment]
@Pascalx77 you could find that version in here https://github.com/AlekseevAV/homebridge-modbus

I'm planning to publish a variation of this to npm to make it easier install on HomeBridge.

**Comment by eliziox** [comment]
﻿Hello Berkus

I tried to use your correction, but I have the following errors :

[4/1/2021, 9:31:16 PM] [Modbus] Connection lost
[4/1/2021, 9:31:21 PM] [Modbus] Reconnecting to 192.168.1.100
[4/1/2021, 9:31:21 PM] [Modbus] Socket connected
[4/1/2021, 9:31:22 PM] [Modbus] error reading modbus { cmd: 'r', type: 'r', add: 1, count: 3 } UserRequestError {
  err: 'ModbusException',
  message: 'A Modbus Exception Occurred - See Response Body',
  response: ModbusTCPResponse {
    _id: 140,
    _protocol: 0,
    _bodyLength: 3,
    _unitId: 1,
    _body: ExceptionResponseBody { _fc: 3, _code: 1 }
  }
}
[4/1/2021, 9:31:22 PM] [Modbus] Connection lost

Can you advise please?

Thanks

JSP

Le 14 mars 2021 à 13:56, Berkus Decker ***@***.***> a écrit :

﻿

@Pascalx77<https://github.com/Pascalx77> you could find that version in here https://github.com/AlekseevAV/homebridge-modbus

I'm planning to publish a variation of this to npm to make it easier install on HomeBridge.

**Comment by sclavel** [comment]
an optional scale parameter is now available in 1.0.2

**Comment by berkus** [comment]
👍🏼 thank you!

**Comment by ghost** [comment]
@sclavel I can't get scale to work nothing happens.
Config 1:
```json
{
    "name": "Außen",
    "type": "TemperatureSensor",
    "CurrentTemperature": {
        "address": "r10201",
        "scale": 100
    }
}
```

Error:
```
[4/18/2022, 11:49:28 PM] [Modbus] Außen Current Temperature 100 => 1327
[4/18/2022, 11:49:28 PM] [homebridge-modbus] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 1327 exceeded maximum of 100. See https://git.io/JtMGR for more info.```

**Comment by ghost** [comment]
Perhaps both need do be named map and not modbusMap?
```
if ('scale' in modbusMap) {
      val = val / modbusMap.scale;
    }
if ('mask' in map) {
      val = val & map.mask;
    }
```

**Comment by sclavel** [comment]
Scale is a multiplier.
"scale": 2, will multiply the modbus value by 2.
"scale": 0.5, will divide the modbus value by 2.

**Comment by ghost** [comment]
@sclavel I fixed my issues renaming modbusMap.scale to map.scale in line 314.

**Comment by eliziox** [comment]
Scale is diviser and not multiplier for register

10 = divised by 10
